language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: i+uUG55jeswvWhwlrjZikxwfmJNUsh0bbDqbLtS55+opB6YKf7lMFIAU6p0qzE8uIyBxs9YYMKdQ8rR+J0uTOiqOktC/ugWuBIWOLCBwjSJ7wZhmiiYM7OQ+RcNOEd+s6KBHrh2xVZXqClyYFEW8m0XIA88q2zmi/gDNLyI/JrlcZ/IR48+UWQYjqR6KQKor0zCXlncxVr4qfXvL1J3H+vwm9esZ9y/8sEH7cV0Xysyn7IN8rb+PXMZKUGhgPCFrXyMEN7ZexpsFuxAihsxF8s8hSBB3K5zGwHbABMUXCYRNIvou+BtAXu2g8HJyUQl9iK48CWc2Fho2lIY7PLnwHLQQo7uKY+BaJRC6MoCaHmDLwEhLwgKiiJNQZpOb+BZ8OAyaneoeiWMMof197ZU/67uvYVIrvwb2CUxG5dlG/ITIrZoOHikjXnoFWXYN7I3G4+4853mWGviIgz4152PnSIHIhllpfAtKe/Z83wPzF6KftfLcmIELKwyiAlCwHHq6CuvBydSv2s5dcV7mT5hAFIjROQESoUKlRS5gMuImb4ZS9qrygSi7gOrbSlsex5I/N6NBYYCLY4NvyOUvWUcpHf8sE37Q7Y5Gbk+zEESSAGVnwhYSZegaKNmoA01jTl+KihSOq3UEi17aqFvwKlVdOTSl13qEthh0BQjBF2KdCSM=
